name: Sync with upstream

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨 3 点运行（UTC 时间）
  workflow_dispatch:     # 允许手动运行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 防止使用默认权限造成冲突

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/MicrosoftDocs/security.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes (without deleting local files)
        run: |
          git merge upstream/main --no-commit --no-ff || true
          # 恢复被删除的文件（如果有）
          git ls-files --deleted -z | xargs -0 git restore || true
          git commit -am "Sync from upstream without removing local files" || echo "Nothing to commit"

      - name: Push changes to fork
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
